# Generated by Django 4.2.2 on 2023-08-21 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_followers_user_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postLiked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLiked', to='network.post')),
                ('whoLiked', models.ManyToManyField(blank=True, null=True, related_name='whoLiked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
