# Generated by Django 4.2.2 on 2023-08-21 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='whoLiked',
        ),
        migrations.AddField(
            model_name='like',
            name='whoLiked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whoLiked', to=settings.AUTH_USER_MODEL),
        ),
    ]
